allowBuilds:
  "@parcel/watcher": false
  esbuild: false
ignoredBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
minimumReleaseAgeExclude:
  - obuild*
  - "@vercel/nft*"
patchedDependencies:
  "@vercel/nft@1.10.2": patches/@vercel__nft@1.10.2.patch
